Ttree:
  Taxonomy:
    managedVocabulary:
      enabled: false
      dimensionsMapping: []

Neos:
  Neos:
    fusion:
      autoInclude:
        Ttree.Taxonomy: true
    userInterface:
      translation:
        autoInclude:
          Ttree.Taxonomy:
            - 'NodeTypes/**/*'

  ContentRepository:
    Search:
      defaultContext:
        TaxonomyIndexing: Ttree\Taxonomy\Eel\IndexingHelper
