Ttree:
  Taxonomy:
    managedVocabulary:
      enabled: false
      dimensionsMapping: []

Neos:
  Neos:
    Ui:
      resources:
        stylesheets:
          'Ttree.Taxonomy:Backend':
            resource: 'resource://Ttree.Taxonomy/Public/Styles/Backend.css'
            position: 'end'
            
    fusion:
      autoInclude:
        Ttree.Taxonomy: true
    userInterface:
      translation:
        autoInclude:
          Ttree.Taxonomy:
            - 'NodeTypes/**/*'

  ContentRepository:
    Search:
      defaultContext:
        TaxonomyIndexing: Ttree\Taxonomy\Eel\IndexingHelper
